### ISSUE TITLE
出现很多KeyError的情况

### ISSUE THREAD

**Issue by bot66** [zchrissirhcz/imageset-viewer#6]
比如KeyError: 'sports ball', KeyError: 'tie', KeyError: 'zebra', KeyError: 'airplane'等

**Comment by bot66** [comment]
git pull 之后出现以上问题

**Comment by zchrissirhcz** [comment]
@bot66 这个是类别没有识别正确。默认调用的是example1()函数，用的是PASCAL VOC的20类。你需要看一下代码中的example2()函数，按照这个函数中指定类别的方式，把你自己数据集的类别写为一个字典。

**Comment by zchrissirhcz** [comment]
@bot66  更新到0.5版本了，现在不必在代码中手动指定类别，直接在GUI界面上选择图片和XML目录，就可以自动识别类别并绘制。如果要指定 “只显示”或“不要显示”特定的类别，则可以按照最新代码中的`example3()`函数做修改。
