### ISSUE TITLE
ImportError: No module named builtins

### ISSUE THREAD

**Issue by kdarras** [zchrissirhcz/imageset-viewer#8]
I followed the installation instructions exactly and everything was successfully installed. However, when I run `python imageset-viewer.py` I get the error in the title

**Comment by zchrissirhcz** [comment]
@kdarras  Hi, I guess this error is under python2 environment. If so, you may try `pip install future` to resolve it. Hope this can be helpful!

**Comment by kdarras** [comment]
Thank you. Running the `pip install future` command gave me `Requirement already satisfied: future in /usr/lib/python3/dist-packages (0.18.2)`
the same error remains
